### ISSUE TITLE
Updated README

### ISSUE THREAD

**Issue by ashishk1994** [peragro/django-project#12]
Hi, 
I am getting below error when following the README.
```
python manage.py loaddata django_project/fixtures/initial_data.json
```
I think it is because I don't have any user in the auth_table. 

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ashish/peragro/django-project-1/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/ashish/peragro/django-project-1/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ashish/peragro/django-project-1/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ashish/peragro/django-project-1/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/ashish/peragro/django-project-1/env/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/ashish/peragro/django-project-1/env/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 106, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/home/ashish/peragro/django-project-1/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 292, in check_constraints
    referenced_table_name, referenced_column_name))
django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'django_project_membership' with primary key '1' has an invalid foreign key: django_project_membership.member_id contains a value '1' that does not have a corresponding value in auth_user.id.

**Comment by ashishk1994** [comment]
It is resolved by creating superuser using python manage.py createsuperuser. I have updated the README. Check the PR https://github.com/peragro/django-project/pull/13
